# Generated by Django 6.0 on 2026-01-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tipo_negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='negocios.tiponegocio'),
        ),
    ]
