# Generated by Django 6.0 on 2026-01-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_servicios', models.PositiveIntegerField()),
                ('max_recursos', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='NegocioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='negocios.negocio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='planes.plan')),
            ],
            options={
                'verbose_name': 'Plan del negocio',
                'verbose_name_plural': 'Planes del negocio',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('negocio', 'activo'), name='un_solo_plan_activo_por_negocio')],
            },
        ),
    ]
