# Generated by Django 6.0 on 2026-01-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_servicios', models.IntegerField()),
                ('max_recursos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NegocioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='negocios.negocio')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='planes.plan')),
            ],
        ),
    ]
