# Generated by Django 6.0 on 2026-01-04 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='negocios.negocio')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='recursos.tiporecurso')),
            ],
        ),
    ]
