# Generated by Django 6.0 on 2026-01-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        ('recursos', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada_cliente', 'Cancelada por cliente'), ('cancelada_negocio', 'Cancelada por negocio'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=30)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='negocios.negocio')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='recursos.recurso')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='servicios.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.usuario')),
            ],
        ),
    ]
