# Generated by Django 6.0 on 2026-01-04 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('intervalo_min', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='recursos.recurso')),
            ],
        ),
    ]
