# Generated by Django 6.0 on 2026-01-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disponibilidad', '0001_initial'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='recursos.recurso'),
        ),
    ]
