# Generated by Django 6.0 on 2026-01-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='dia_semana',
        ),
    ]
